import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'
import './globals.css'

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-sans',
})

const angst = localFont({
	src: [
		{
			path: '../../public/fonts/angst/Angst-Thin.woff2',
			weight: '200',
			style: 'light',
		},
		{
			path: '../../public/fonts/angst/Angst-Normal.woff2',
			weight: '400',
			style: 'normal',
		},
		{
			path: '../../public/fonts/angst/Angst-Bold.woff2',
			weight: '400',
			style: 'bold',
		},
	],
	variable: '--font-angst',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${inter.variable} ${angst.variable} antialiased`}>
				{children}
			</body>
		</html>
	)
}
